export const downloadFile = (filename: string, content: string, contentType: string = 'text/plain') => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const generateSQL = (schema: any): string => {
    let sql = `-- Database Schema Export\n-- Generated by Caffeine Viz\n\n`;

    // Create Tables
    schema.tables.forEach((table: any) => {
        sql += `CREATE TABLE ${table.name} (\n`;
        const cols = table.columns.map((col: any) => {
            let line = `    ${col.name} ${col.type.toUpperCase()}`;
            if (col.primary_key) line += ' PRIMARY KEY';
            if (col.unique) line += ' UNIQUE';
            if (col.default !== undefined) {
                const defVal = typeof col.default === 'string' ? `'${col.default}'` : col.default;
                line += ` DEFAULT ${defVal}`;
            }
            return line;
        });
        sql += cols.join(',\n');
        sql += `\n);\n\n`;
    });

    // Add Relationships (Foreign Keys)
    sql += `-- Relationships\n`;
    schema.relationships.forEach((rel: any) => {
        const [table, col] = rel.from.split('.');
        const [targetTable, targetCol] = rel.to.split('.');
        if (table && targetTable) {
            sql += `ALTER TABLE ${table} ADD CONSTRAINT fk_${table}_${targetTable} FOREIGN KEY (${col}) REFERENCES ${targetTable}(${targetCol});\n`;
        }
    });

    return sql;
};

export const generateMarkdownDocs = (apiDocs: any): string => {
    let md = `# API Documentation\n\n`;

    Object.entries(apiDocs).forEach(([key, section]: [string, any]) => {
        md += `## ${section.title || key}\n\n`;
        section.endpoints.forEach((ep: any) => {
            md += `### ${ep.method} ${ep.path}\n`;
            md += `- **Description**: ${ep.desc}\n`;
            md += `- **Body**: \`${ep.body}\`\n`;
            md += `- **Response**: \`${ep.response}\`\n\n`;
        });
        md += `---\n\n`;
    });

    return md;
};
